### ISSUE TITLE
getRidesBySurfspot retornando 204 no content

### ISSUE THREAD

**Issue by tiagoporangaba** [temantrip/temantrip-backend#1]
É retornado no content para um pico (exemplo id = 1) quando o serviço getSumOfRides retorna viagen para o pico com id = 1.

**Comment by tiagoporangaba** [comment]
Permitir o campo "nickname" no serviço surfer/put. Retornar o mesmo campo no surfer/get.

**Comment by jeanstreleski** [comment]
Done.
