### ISSUE TITLE
getFeed para usuário novo não está retornando conteúdo

### ISSUE THREAD

**Issue by tiagoporangaba** [temantrip/temantrip-backend#4]

**Comment by jeanstreleski** [comment]
Mano,

Pelo que falamos no dia, está na chamada do app, já que você está sempre chamando o feed do cara e não o feed geral. Basta chamar o feed sem passar parametros.

**Comment by tiagoporangaba** [comment]
sim! ja testei sem parametros. funcionou!

Em terça-feira, 21 de julho de 2015, jeanstreleski <notifications@github.com>
escreveu:

> Mano,
>
> Pelo que falamos no dia, está na chamada do app, já que você está sempre
> chamando o feed do cara e não o feed geral. Basta chamar o feed sem passar
> parametros.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/temantrip/temantrip-backend/issues/4#issuecomment-123516273>
> .
>


-- 
Sincerely,
Tiago Porangaba
