### ISSUE TITLE
Contrato endpoint do To Indo e Ja Fui

### ISSUE THREAD

**Issue by tiagoporangaba** [temantrip/temantrip-backend#5]
Sugestão de mensagem de input para os dois:

{
  "historyId": 7
  "surferOwner": {
        "facebook_id": "123456"
  } 
}

Assim vou criar um POJO do meu lado tanto para Wish quanto para Done, com a propriedade historyId do tipo inteiro e propriedade surferOwner do tipo Surfer.

Output: Ao invés de retornar só 200, retorne também a mensagem com o total de wishes e dones com o seguinte contrato:

{
    "total": 392
}

Assim, quando eu der like, e paralelamente alguém der like, já atualizo com a quantidade mais recente de likes.

**Comment by jeanstreleski** [comment]
Boa sugestão

Done!

o contrato de input ficou assim para ambos

{
 "historyId": 130,
 "surferOwner": {
        "facebook_id": "123456"
  } 
}

OUTPUT:

{
"total": 4
}

**Comment by tiagoporangaba** [comment]
tá dando esse pau aqui!

testei algumas vezes com histórias diferentes... vamos ver isso hoje.

<img width="642" alt="screen shot 2015-07-22 at 2 46 17 pm" src="https://cloud.githubusercontent.com/assets/1115173/8832622/7edb5c0c-3080-11e5-9069-ab7319149d4b.png">

**Comment by jeanstreleski** [comment]
Posso estar enganado mas não falta uma vírgula depois do campo historyId ?

**Comment by tiagoporangaba** [comment]
Jeanzin, faltava a virgulha sim. Coloquei ela agora e tá dando 500 denovo. Veja ai:

![image](https://cloud.githubusercontent.com/assets/1115173/9706218/aa991010-54b5-11e5-9224-55c27478c695.png)

**Comment by jeanstreleski** [comment]
Foi cagada minha. Reverti um commit no ultimo pacote. Agora tá certo de novo. SEgue o modelo acima.
