### ISSUE TITLE
Wish and Doing - Add or Delete - Returning 200 OK but with Error in content

### ISSUE THREAD

**Issue by tiagoporangaba** [temantrip/temantrip-backend#9]
![image](https://cloud.githubusercontent.com/assets/1115173/11170593/17952258-8bc0-11e5-9092-6ec49dbdda95.png)

![image](https://cloud.githubusercontent.com/assets/1115173/11170618/dac3a588-8bc0-11e5-9292-6405a56321a9.png)

**Comment by jeanstreleski** [comment]
Tem dois erros ai.

O contrato do meu DHC está incorreto. Ao invés de enviar um tipo complexo para historyOfWish, você pode enviar o parametro historyId. Tanto para toindo quando para jaFui. 

Também implementei o retorno de erro correto para estourar erro 500. O código de história que você mandou não existe.

Publico em breve.
